version: '3.4'
services:
  db:
    image: mysql:9.1.0
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: rest_with_spring
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - gabriel-network
  rest-with-sring-gabriel:
    image: rest-with-sring-gabriel
    build: .
    working_dir: .
    ports:
      - 80:80
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_with_spring?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - gabriel-network
networks:
  gabriel-network:
    driver: bridge