name: Continous Integration and Delivery with Github Actions

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: actions/checkout@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build Application .jar
      run: mvn clean package

    - name: Docker Compose Build
      run: docker compose up --build

    - name: Push to Dockerhub Container Registry
      run: |
        docker tag rest-with-sring-gabriel ${{ secrets.DOCKER_USERNAME }}/rest-with-sring-gabriel
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-sring-gabriel

